# Python的内建对象数组可以有三种形式：

List 列表：[1, 2, 3]

Tuple 元组：(1, 2, 3, 4, 5)

Dict 字典：{A:1, B:2}

列表为大家所熟知，元组与列表相似，区别在于元组里的值无法修改。字典是另一种可变容器模型，且可存储任意类型对象。字典对象由键和值组成，每个键值(key=>value)对用冒号(:)分割，每个对之间用逗号(,)分割，整个字典包括在花括号({})中

Python中也提供了一个array模块，只保存数值，不支持多维运算，也没有各种运算的函数，因此不适合做数组运算。NumPy诞生弥补了这些不足。

numpy有2种基本对象，ndarray（N-dimensional array object）和 ufunc（universal functionobject），ndarray是存储单一数据类型的多维数组， 而ufunc则是能够对数组进行处理的函数

# 通过list 创建numpy的ndarray数组

In [1]:
import numpy as np # 导入numpy包，并重名

list_1=[1,2,3,4]
list_1
print(type(list_1))

<class 'list'>


In [3]:
array_1=np.array(list_1)
array_1
print(type(array_1))

<class 'numpy.ndarray'>


In [2]:
list_2=[5,6,7,8]
array_2=np.array([list_1,list_2]) # 创建二维数组
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 数组的属性及说明

在NumPy中维度(dimensions)叫做轴(axes)，轴的个数叫做秩(rank)。 例如，在3D空间一个点的坐标[1, 2, 3]是一个秩为1的数组，因为它只有一个轴。又例如，在以下例子中，数组的秩为2(它有两个维度).

In [3]:
print('数组轴的个数：',array_2.ndim) # ndarray.ndim:数组轴的个数，在python的世界中，轴的个数被称作秩

数组轴的个数： 2


In [6]:
print('数组的维度：',array_2.shape) # ndarray.shape:数组的维度。这是一个指示数组在每个维度上大小的整数元组。例如一个n排m列的矩阵

数组的维度： (2, 4)


In [7]:
print('数组元素的个数：',array_2.size) # ndarray.size：数组元素的总个数，等于shape属性中元组元素的乘积。

数组元素的个数： 8


In [4]:
print('数组中每个元素的大小：',array_2.itemsize) # ndarray.itemsize：数组中每个元素的字节大小。
                                                 # 例如，一个元素类型为float64的数组itemsiz属性值为8(=64/8)。

数组中每个元素的大小： 4


In [9]:
print('数组类型为：',array_2.dtype) # ndarray.dtype：一个用来描述数组中元素类型的对象，可以通过创造或指定dtype使用标准Python类型。
                                    # 另外NumPy提供它自己的数据类型。

数组类型为： int32


In [10]:
array_3=np.array([[1.0,2,3],[4.0,5,6]])
print('数组类型为：',array_3.dtype)

数组类型为： float64


In [11]:
print('数组元素的缓冲区',array_2.data) # ndarray.data：包含实际数组元素的缓冲区，
                                       # 通常我们不需要使用这个属性，因为我们总是通过索引来使用数组中的元素。

数组元素的缓冲区 <memory at 0x0000006E324D2708>


# 数组的类型

Numpy的基本数据类型 bool_,int_,intc,intp,int8,int16,int32,int64,uint8,unint16,uint32,uint64,float_,float16,float32,float64,
complex_,complex64,complex128

In [5]:
array_4=np.array(list_1,dtype=np.float) # 也可在定义数组时指定数据类型
array_4

array([1., 2., 3., 4.])

# 用arange创建ndarray数组

In [6]:
array_5=np.arange(1,10) # 不包括10 
array_5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array_6=np.arange(1,10,2) # 不包括10 
array_6

array([1, 3, 5, 7, 9])

# 利用random快速创建数组

均匀分布和正态分布的随机函数区别： 使用的随机数函数rand()产生的是服从均匀分布的随机数，能够模拟等概率出现的情况，例如扔一个骰子，1到6点的概率应该相等。

但现实生活中更多的随机现象是符合正态分布的，例如20岁成年人的体重分布等。 假如我们在制作一个游戏，要随机设定许多人为角色的身高，如果还用均匀分布，生成从140 到 220 之间的数字，就会发现每个身高段的人数是一样多的， 这是比较无趣的，这样的世界也与我们习惯不同，现实应该是特别高和特别矮的都很少，处于中间的人数最多，这就要求随机函数符合正态分布。

In [16]:
print('均匀分布随机函数Rand：')
print(np.random.rand()) # 服从均匀分布0-1之间随机数
print(np.random.rand(10)) # 服从均匀分布0-1之间随机数
print(np.random.rand(2,4)) # 2行4列的随机数矩阵 ，服从均匀分布0-1之间随机数

均匀分布随机函数Rand：
0.11849149872723874
[0.18617327 0.59997583 0.07239687 0.09485042 0.82406231 0.57062223
 0.78703433 0.71352687 0.19632135 0.12967194]
[[0.30412967 0.63823635 0.29374466 0.30959633]
 [0.52218432 0.93623654 0.76320713 0.06525753]]


In [17]:
print('正态分布随机函数Randn：')
print(np.random.randn(2,4)) # 2行4列的随机数矩阵 ，服从正态分布0-1之间随机数

正态分布随机函数Randn：
[[ 0.56015857 -0.6989816   0.59975918  0.34867323]
 [-3.09917183  1.86324791 -0.95931972 -1.20167071]]


In [78]:
print('RandInt:')
print(np.random.randint(1,10)) # 生成1-10的随机整数

RandInt:
3


In [94]:
print('RandInt:')
print(np.random.randint(10,20,5)) # 生成5个10-20的随机整数

RandInt:
[13 15 13 16 13]


In [93]:
print('Choice:')
print(np.random.choice([10,20,30,2,8])) # 尽在给出的可选值内产生随机数

Choice:
8


# 用linspace和logspace函数创建数组

In [22]:
array_7=np.linspace(1,10,5) # linspace通过指定开始值、终值和元素个数来创建一维数组，默认设置包括终值，等差数列分布
array_7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
array_8=np.logspace(1,10,5) # logspace和linspace函数类似，它是来创建等比数列的。
array_8

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

# 创建特殊数组矩阵

In [24]:
np.zeros(5) # 全0矩阵

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.eye(5) # 单位矩阵

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.ones([4,3]) # 全1矩阵

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.diag([1,2,3,4]) # 对角线数组，即除对角线以外的其他元素都为0，对角线上的元素可以是0或其他值

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# 数组的访问（索引 和 切片）

In [29]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[1] # 下标从0 开始

2

In [31]:
a[1:5] # 切片  不包含下标为5的元素

array([2, 3, 4, 5])

In [32]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b[1][0]

4

In [34]:
b[1,0]

4

In [35]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
c[:2,1:] # 二维数组切片，   第0行到第2行 0 1  第1列到最后 取值 1 2

array([[2, 3],
       [5, 6]])

# 数组形态变化

In [37]:
arr=np.arange(12)
print('创建一维数组为：',arr)

创建一维数组为： [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
print('新的数组为：\n',arr.reshape(3,4)) # 设置数组的形状

新的数组为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
print('新的数组维度为：\n',arr.reshape(3,4).ndim)

新的数组维度为：
 2


In [41]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [43]:
arr=arr.reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
print('数组展平后为：\n',arr.ravel()) # 数组横向展平

数组展平后为：
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [45]:
print('数组展平后为：\n',arr.flatten()) # 数组横向展平

数组展平后为：
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [46]:
print('数组展平后为：\n',arr.flatten('F')) # 数组纵向展平

数组展平后为：
 [ 0  4  8  1  5  9  2  6 10  3  7 11]


In [49]:
arr1=np.arange(12).reshape(3,4)
print('创建数组1为：\n',arr1)

创建数组1为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
arr2=arr1*3
print('创建数组1为：\n',arr2)

创建数组1为：
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [52]:
print('横向组合为：\n',np.hstack((arr1,arr2)))

横向组合为：
 [[ 0  1  2  3  0  3  6  9]
 [ 4  5  6  7 12 15 18 21]
 [ 8  9 10 11 24 27 30 33]]


In [53]:
print('纵向组合为：\n',np.vstack((arr1,arr2)))

纵向组合为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [99]:
arr=np.arange(16).reshape(4,4)
print('创建数组1为：\n',arr)

创建数组1为：
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [103]:
print('横向分割为：\n',np.hsplit(arr,2))

横向分割为：
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [56]:
print('纵向分割为：\n',np.vsplit(arr,2))

纵向分割为：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [57]:
print('纵向分割为：\n',np.split(arr,2,axis=0))

纵向分割为：
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# NumPy的ndarray 快速的元素级数组函数

In [58]:
print(np.arange(1,11).reshape([2,-1])) # reshape中-1 为系统自动计算第二维个数

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [60]:
array=np.arange(1,11).reshape([2,-1])
print('Exp:')
print(np.exp(array))
print('Exp2:')
print(np.exp2(array))
print('Sqrt:')
print(np.sqrt(array))
print('Sin:')
print(np.sin(array))
print('Log:')
print(np.log(array))

Exp:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]]
Exp2:
[[   2.    4.    8.   16.   32.]
 [  64.  128.  256.  512. 1024.]]
Sqrt:
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
Sin:
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]]
Log:
[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]]


# 数组的运算

In [61]:
a=np.random.randint(10,size=20).reshape(4,5)
a

array([[6, 3, 8, 3, 0],
       [9, 8, 7, 3, 0],
       [0, 6, 8, 7, 7],
       [5, 9, 8, 7, 0]])

In [62]:
b=np.random.randint(10,size=20).reshape(4,5)
b

array([[2, 4, 0, 2, 8],
       [5, 7, 4, 8, 8],
       [7, 1, 1, 5, 0],
       [4, 4, 2, 0, 1]])

In [63]:
a+b

array([[ 8,  7,  8,  5,  8],
       [14, 15, 11, 11,  8],
       [ 7,  7,  9, 12,  7],
       [ 9, 13, 10,  7,  1]])

In [64]:
a-b

array([[ 4, -1,  8,  1, -8],
       [ 4,  1,  3, -5, -8],
       [-7,  5,  7,  2,  7],
       [ 1,  5,  6,  7, -1]])

In [65]:
a*b

array([[12, 12,  0,  6,  0],
       [45, 56, 28, 24,  0],
       [ 0,  6,  8, 35,  0],
       [20, 36, 16,  0,  0]])

In [66]:
a/b

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[3.        , 0.75      ,        inf, 1.5       , 0.        ],
       [1.8       , 1.14285714, 1.75      , 0.375     , 0.        ],
       [0.        , 6.        , 8.        , 1.4       ,        inf],
       [1.25      , 2.25      , 4.        ,        inf, 0.        ]])

# 创建NumPy矩阵以及矩阵的运算

矩阵是继承自NumPy数组对象的二维数组对象，矩阵是narray的子类，使用mat、matrix、bmat函数创建

In [69]:
matr1=np.mat('1,2,3;4,5,6;7,8,9')
print('创建矩阵为：\n',matr1)

创建矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
matr2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print('创建矩阵为：\n',matr2)

创建矩阵为：
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
arr1=np.eye(3)
print('创建数组1为：\n',arr1)

创建数组1为：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
arr2=3*arr1
print('创建数组2为：\n',arr2)

创建数组2为：
 [[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [76]:
print('创建矩阵为：\n',np.bmat('arr1 arr2;arr1 arr2'))

创建矩阵为：
 [[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]


In [77]:
matr2=matr1*3
print('创建矩阵为：\n',matr2)

创建矩阵为：
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [78]:
print('矩阵相加为：\n',matr1+matr2)

矩阵相加为：
 [[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [79]:
print('矩阵相减为：\n',matr1-matr2)

矩阵相减为：
 [[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


In [80]:
print('矩阵相乘为：\n',matr1*matr2)

矩阵相乘为：
 [[ 90 108 126]
 [198 243 288]
 [306 378 450]]


In [81]:
print('矩阵相除为：\n',matr1/matr2)

矩阵相除为：
 [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [82]:
print('矩阵对应元素相乘为：\n',np.multiply(matr1,matr2)) # 对应元素相乘

矩阵对应元素相乘为：
 [[  3  12  27]
 [ 48  75 108]
 [147 192 243]]


In [105]:
# 线性代数
# numpy.linalg模块包含线性代数的函数。使用这个模块，可以计算逆矩阵、求特征值、解线性方程组以及求解行列式等。

from numpy.linalg import *

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [106]:
m=np.array([[1.,2.],[-1.,-3.]])
print(m)

[[ 1.  2.]
 [-1. -3.]]


In [107]:
print('Inv:')
print(inv(m))

Inv:
[[ 3.  2.]
 [-1. -1.]]


In [108]:
print('T:')
print(m.transpose()) #矩阵的转置

T:
[[ 1. -1.]
 [ 2. -3.]]


In [109]:
print('Det:')
print(det(m))  # 行列式的值1*-3 -（2*（-1））

Det:
-1.0


In [110]:
#解线性方程组

y=np.array([[5.],[7.]])
print('Solve')
print(m)

# x+2y = 5
#-x-3y = 7

print(solve(m,y))

Solve
[[ 1.  2.]
 [-1. -3.]]
[[ 29.]
 [-12.]]
